services:

  gitea:
    image: gitea/gitea:latest-rootless
    restart: always
    dns: 8.8.8.8
    networks:
      - ecosystem
    ports:
      - "3001:3000"
      - "2221:22"
    volumes:
      - gitea_data:/var/lib/gitea
      - gitea_config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__server__ROOT_URL=http://$IP:3000/
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/var/lib/gitea/data/gitea.db
      - GITEA__database__HOST=...
      - GITEA__database__NAME=...
      - GITEA__database__USER=...
      - GITEA__database__PASSWD=...

  jenkins:
    image: jenkinsci/blueocean:1.25.7
    restart: always
    networks:
      - ecosystem
    ports:
      - "8080:8080"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /run/user/1000/docker.sock:/var/run/docker.sock

volumes:
  gitea_config:
  gitea_data:
  jenkins_data:

networks:
  ecosystem:
